
node() {

    stage('Checkout') {

        // Checkout files.
        checkout([
            $class: 'GitSCM',
            branches: [[name: 'main']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [], submoduleCfg: [],
            userRemoteConfigs: [[
                name: 'github',
                url: 'https://github.com/dkchrome/ios-jenkins.git'
            ]]
        ])
    }

        // Build and Test
        //sh 'xcodebuild -project ./StockFeed/StockFeed.xcodeproj -scheme "StockFeed" -configuration "Debug" build test -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4" '

        stage 'Build'

            sh 'xcodebuild -project ./StockFeed/StockFeed.xcodeproj -scheme "StockFeed" -configuration "Debug" build -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4" '

    
        stage 'Test'
        sh 'xcodebuild -project ./StockFeed/StockFeed.xcodeproj -scheme "StockFeed" -configuration "Debug" test -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4" '

    
}
